Import required libraries

In [1]:
from PIL import Image
import numpy as np
import math

" "=255, .=249, '=245, -=247, _=245, :=244, "=236, *=235, /=231, +=230, ==227, (=226, [= 221, ?= 220, {= 216, #=205, §=198, %=191, $=186, @=162

In [ ]:
asciiTable=["@", "$", "%", "§", "#", "{", "?", "[", "(", "=", "+", "/", "*", "\"", ":", "_", "-", "'", ".", " "]
image_path = "C:\\Users\\TimHeil\\Pictures\\Screenshots\\dot.gif"

image = Image.open(image_path)
image = image.convert("L")
width, height = image.size
scaleFactor = 8
print(width, height)
print(len(asciiTable))

In [4]:
image_matrix = np.array(image)

avgDarkness = np.int64(0)
for row in image_matrix:
    for elem in row:
        avgDarkness += elem

avgDarkness=int((avgDarkness)/(width*height))      
print(avgDarkness)


249


In [5]:
asciiIndex = np.int64(np.floor((avgDarkness/255)*19))
asciiChar = asciiTable[asciiIndex]
print(asciiChar)

.


In [6]:
avgDarkness = np.int64(0)
yIterations = np.floor(width/8)
xIterations = np.floor(height/8)
chunksize = 8



In [ ]:
array2d = [["1", "2", "3", "4", "5", "6"], ["1", "2", "3", "4", "5", "6"], ["1", "2", "3", "4", "5", "6"]]
array = ["1", "2", "3", "4", "5", "6"]

for i in range(0, 3, 1):
   for j in range(0, 6, 1):
       print(array2d[i][j])

avg = 0

for i in range(0, len(array), 1):
    avg+=i
    
print(avg/len(array))


In [ ]:
array = np.array([[1, 2, 3, 4, 5, 6],[7, 8, 9, 10, 11, 12],[13, 14, 15, 16, 17, 18]])

row = array[0]

print(row)

avgCounter = 0
avg = 0

for i in row:
    avg+=i
    if avgCounter == 1:
        print(avg/2)
        avgCounter=0
        avg=0
    else:
        avgCounter+=1
    



[1 2 3 4 5 6]
1.5
3.5
5.5


In [ ]:
from PIL import Image
import numpy as np
import math

asciiTable=["@", "$", "%", "§", "#", "{", "?", "[", "(", "=", "+", "/", "*", "\"", ":", "_", "-", "'", ".", " "]
image_path = "path/to/image"

image = Image.open(image_path)
image = image.convert("L")
width, height = image.size
scaleFactor = 8
print(width, height)
print(len(asciiTable))
chunkWidth = 8
chunkHeight = 16

image_matrix = np.array(image)

def getAverageMatrixDarkness(image_submatrix):
    avgMatrixDarkness = np.int64(0)
    for row in image_submatrix:
        for elem in row:
            avgMatrixDarkness += elem
    avgMatrixDarkness=int((avgMatrixDarkness)/(chunkWidth*chunkHeight))      
    return avgMatrixDarkness

def getAsciiCharacter(avgDarkness):
    asciiIndex = np.int64(np.floor((avgDarkness/255)*19))
    asciiChar = asciiTable[asciiIndex]
    return asciiChar

def getSubmatrix(matrix, start_row, start_col):
    return matrix[start_row:start_row + chunkWidth, start_col:start_col + chunkHeight]

submatrix = getSubmatrix(image_matrix, 0, 0)
print(submatrix)

def convertImage(image_matrix):
    for y in range(0, height, chunkHeight):
        print("\n" ,end="")
        for x in range(0, width, chunkWidth):
            print(getAsciiCharacter(getAverageMatrixDarkness(getSubmatrix(image_matrix, y, x))), end="")
        
convertImage(image_matrix)

736 736
20
[[253 253 253 253 253 253 253 253 253 253 253 253 253 253 253 253]
 [253 253 253 253 253 253 253 253 253 253 253 253 253 253 253 253]
 [253 253 253 253 253 253 253 253 253 253 253 253 253 253 253 253]
 [253 253 253 253 253 253 253 253 253 253 253 253 253 253 253 253]
 [253 253 253 253 253 253 253 253 253 253 253 253 253 253 253 253]
 [253 253 253 253 253 253 253 253 253 253 253 253 253 253 253 253]
 [253 253 253 253 253 253 253 253 253 253 253 253 253 253 253 253]
 [253 253 253 253 253 253 253 253 253 253 253 253 253 253 253 253]]

...................................'...'"[%$@@@$#=_........................................=
.................................'.._[%@@@@@@@@@@@@@%(_....................................=
.................................._?$@@@@@@@@@@@@@§#§@@{:..................................=
.................................:#@@@@@@@@@@@@@@$#?{§$@$(-................................=
................................_?@@@@@@@@@@@@@@@$$$@@@@@@?_...................

In [7]:
print("abc", end="")
print("def", end="")

abcdef