Import required libraries

In [26]:
from PIL import Image
import numpy as np
import math

Convert image to grayscale

In [28]:
image_path = "C:\\Users\\TimHeil\\Pictures\\Screenshots\\untitled.gif"
image = Image.open(image_path)
image = image.convert("L")
image.show()
width, height = image.size
print(width, height)
image_matrix = np.array(image)

print(image_matrix)

avgDarkness = np.int64(0)
for row in image_matrix:
    for elem in row:
        avgDarkness += elem
        
print(np.floor(avgDarkness/64))

8 8
[[255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255]
 [255 255   0 255 255   0 255 255]
 [255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255]
 [255   0 255 255 255 255   0 255]
 [255 255   0   0   0   0 255 255]
 [255 255 255 255 255 255 255 255]]
223.0
